services:
  - type: web
    name: aniwatch-api
    runtime: docker
    repo: https://github.com/anime-kun32/aniwatch-api.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 4000
