services:
  - type: web
    name: aniwatch-api
    runtime: node
    repo: https://github.com/anime-kun32/aniwatch-api.net.git
    plan: free
    branch: main
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: "4000"
